# pyproject.toml - Minimal Dependencies Version

[project]
name = "nemo-forced-aligner"
version = "0.1.0"
description = "Simple NeMo forced aligner for Kaggle/Colab integration"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "Apache-2.0" }
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
keywords = [
    "nemo",
    "forced-alignment",
    "asr",
    "speech-recognition",
    "kaggle",
    "colab"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

# Minimal core dependencies only
dependencies = [
    "nemo_toolkit[asr]>=1.18.0",  # Changed from [all] to [asr] only
    "torch>=1.13.0",
    "librosa>=0.10.0",
    "soundfile>=0.12.0",
    "numpy>=1.21.0",
    "omegaconf>=2.0.0",
]

# Optional dependencies
[project.optional-dependencies]
# GPU acceleration (kept as requested)
gpu = [
    "numba>=0.56.0",
    "pynvml>=11.0.0",
]

# Development dependencies (minimal set)
dev = [
    "pytest>=7.0.0",
]

[project.urls]
Homepage = "https://github.com/jamanz/al-gner"
Repository = "https://github.com/jamanz/al-gner.git"

# Package discovery
[tool.setuptools]
packages = ["nemo_forced_aligner"]

# Build system requirements
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"